#! /bin/bash

if [ $# != 1 ]
then
    echo "usage: load elf"
    exit 1
fi

file=$1

cat > TMP.gdb <<EOF
target extended-remote /dev/ttyBmpGdb
monitor swdp_scan
monitor traceswo 
attach 1
load $file
EOF


arm-gdb -n --batch -x TMP.gdb $file

