#! /bin/bash

if [ $# != 1 ]
then
    echo "usage: load elf"
    exit 1
fi

file=$1

cat > TMP.gdb <<EOF
target extended-remote /dev/serial/by-id/usb-Black_Sphere_Technologies_Black_Magic_Probe_E2E99CC0-if00
monitor swdp_scan
attach 1
load $file
EOF


arm-gdb -n --batch -x TMP.gdb $file

