/* generated by mkregs.h */
#define DBG_DBGMCU_CR (*(unsigned int volatile *)0xe0042004)
#define RCC_CR (*(unsigned int volatile *)0x40023800)
#define RCC_PLLCFGR (*(unsigned int volatile *)0x40023804)
#define RCC_CFGR (*(unsigned int volatile *)0x40023808)
#define RCC_AHB1ENR (*(unsigned int volatile *)0x40023830)
#define GPIOA_MODER (*(unsigned int volatile *)0x40020000)
#define GPIOA_BSRR (*(unsigned int volatile *)0x40020018)
#define C_ADC_CCR (*(unsigned int volatile *)0x40012304)
#define FLASH_ACR (*(unsigned int volatile *)0x40023c00)

#define RCC_CR_PLLRDY 0x2000000
#define RCC_CR_PLLON 0x1000000
#define RCC_CR_HSERDY 0x20000
#define RCC_CR_HSEON 0x10000
#define RCC_AHB1ENR_GPIOAEN 0x1
