/* generated by mkregs.h */
#define RCC_AHB1ENR (*(unsigned int volatile *)0x40023830)
#define GPIOA_MODER (*(unsigned int volatile *)0x40020000)
#define GPIOA_BSRR (*(unsigned int volatile *)0x40020018)

#define RCC_AHB1ENR_GPIOAEN 0x1
