/* generated by mkregs.h */
#define DBG_DBGMCU_CR (*(unsigned int volatile *)0xe0042004)
#define DMA1_LISR (*(unsigned int volatile *)0x40026000)
#define DMA1_HISR (*(unsigned int volatile *)0x40026004)
#define DMA1_S1CR (*(unsigned int volatile *)0x40026028)
#define DMA1_S1NDTR (*(unsigned int volatile *)0x4002602c)
#define DMA1_S1PAR (*(unsigned int volatile *)0x40026030)
#define DMA1_S1M0AR (*(unsigned int volatile *)0x40026034)
#define RCC_CR (*(unsigned int volatile *)0x40023800)
#define RCC_PLLCFGR (*(unsigned int volatile *)0x40023804)
#define RCC_CFGR (*(unsigned int volatile *)0x40023808)
#define RCC_AHB1ENR (*(unsigned int volatile *)0x40023830)
#define RCC_APB1ENR (*(unsigned int volatile *)0x40023840)
#define GPIOB_MODER (*(unsigned int volatile *)0x40020400)
#define GPIOB_BSRR (*(unsigned int volatile *)0x40020418)
#define GPIOB_AFRH (*(unsigned int volatile *)0x40020424)
#define GPIOA_MODER (*(unsigned int volatile *)0x40020000)
#define USART3_SR (*(unsigned int volatile *)0x40004800)
#define USART3_DR (*(unsigned int volatile *)0x40004804)
#define USART3_BRR (*(unsigned int volatile *)0x40004808)
#define USART3_CR1 (*(unsigned int volatile *)0x4000480c)
#define USART3_CR3 (*(unsigned int volatile *)0x40004814)
#define C_ADC_CCR (*(unsigned int volatile *)0x40012304)
#define FLASH_ACR (*(unsigned int volatile *)0x40023c00)

#define RCC_CR_PLLRDY 0x2000000
#define RCC_CR_PLLON 0x1000000
#define RCC_CR_HSERDY 0x20000
#define RCC_CR_HSEON 0x10000
#define RCC_AHB1ENR_DMA1EN 0x200000
#define RCC_AHB1ENR_GPIOBEN 0x2
#define RCC_AHB1ENR_GPIOAEN 0x1
#define RCC_APB1ENR_USART3EN 0x40000
#define USART_SR_RXNE 0x20
#define USART_CR1_UE 0x2000
#define USART_CR1_TE 0x8
#define USART_CR1_RE 0x4
#define USART_CR3_DMAR 0x40
